apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    my-demo-label: my-demo-value
spec:
  selector:
    matchLabels:
      app: welcome
  template:
    metadata:
      labels:
        app: welcome
    spec:
      containers:
      - image: fpommerening/container-training:webapp-v3
        name: app